### ISSUE TITLE
Swift apps are missing some files

### ISSUE THREAD

**Issue by molinch** [nanonation/floatsign#4]
It is quite strange I used floatsign for many projects but there seems to be an issue with Swift apps. It won't include some necessary files.
I get the following output when using floatsign:

<pre>
Resigning embedded frameworks using certificate: 'iPhone Distribution: xxxxxx'
Ignoring non-framework: _floatsignTemp/Payload/xxxxxx.app/Frameworks/libswiftCore.dylib
Ignoring non-framework: _floatsignTemp/Payload/xxxxxx.app/Frameworks/libswiftCoreGraphics.dylib
Ignoring non-framework: _floatsignTemp/Payload/txxxxxx.app/Frameworks/libswiftCoreImage.dylib
Ignoring non-framework: _floatsignTemp/Payload/xxxxxx.app/Frameworks/libswiftDarwin.dylib
Ignoring non-framework: _floatsignTemp/Payload/xxxxxx.app/Frameworks/libswiftDispatch.dylib
Ignoring non-framework: _floatsignTemp/Payload/xxxxxx.app/Frameworks/libswiftFoundation.dylib
Ignoring non-framework: _floatsignTemp/Payload/xxxxxx.app/Frameworks/libswiftObjectiveC.dylib
Ignoring non-framework: _floatsignTemp/Payload/xxxxxx.app/Frameworks/libswiftSecurity.dylib
Ignoring non-framework: _floatsignTemp/Payload/xxxxxx.app/Frameworks/libswiftUIKit.dylib
</pre>

Do you have an idea?

**Comment by molinch** [comment]
Ok found the solution: we need to codesign dylibs found in .app/Frameworks/

**Comment by djtarazona** [comment]
I'm having the same issue.

**Comment by sudhanshutil** [comment]
I am also having the same issue. But can't understand how to use your solution?

**Comment by GoannaGuy** [comment]
Sudhanshu,

We merged a pull request from 'kommen' back in August of this year that added detection and re-code signing of any files ending with the ‘.dylib' extension found in the application’s ‘Frameworks' directory. Prior to that we were only detecting/re-code signing things that ended in ‘.framework’. 

If you are using an older version of floatSign, please try the current one. Otherwise, can you provide any details on the specific problem you are seeing? A copy of the output from the run of floatSign may help.

Thanks,

-=- John
